### ISSUE TITLE
Possible Infinite Loop with getFluidHeight()

### ISSUE THREAD

**Issue by SonOfTheStars** [BluSunrize/AquaTweaks#4]
@BluSunrize Aquatweaks creates an Infinite Loop sometimes.

Proof: https://www.dropbox.com/s/d12fg0hcjjn7gyq/AQT_IL_FREEZE_SNAP1.nps?dl=0
Minecraft freezes and Constantly Occupies 13% CPU and (due to many mods) 2.8GB RAM

**Comment by Haggle1996** [comment]
Can confirm, watching aquatweaks through VisualVM. Hangs in an infinite loop in getFluidHeight()

**Comment by lashtear** [comment]
"Client thread" #1 prio=5 os_prio=0 tid=0x000001ca0f4cc800 nid=0x54b8 runnable [0x000000171ecfa000]
   java.lang.Thread.State: RUNNABLE
        at blusunrize.aquatweaks.FluidUtils.canConnectAquaConnectable(FluidUtils.java:416)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:142)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:142)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:142)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:142)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:142)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:142)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:142)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:142)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:142)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:142)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.getFluidHeight(FluidUtils.java:133)
        at blusunrize.aquatweaks.FluidUtils.tessellateFluidBlock(FluidUtils.java:191)
        at blusunrize.aquatweaks.AquaEventHandler.handleWaterRendering(AquaEventHandler.java:42)
        at blusunrize.aquatweaks.AquaEventHandler.onWorldRenderMid(AquaEventHandler.java:26)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_1171_AquaEventHandler_onWorldRenderMid_RenderWorldEventMid.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
        at blusunrize.aquatweaks.core.AquaTweaksCoreTransformer.fireMidRenderEvent(AquaTweaksCoreTransformer.java:105)
        at net.minecraft.client.renderer.WorldRenderer.func_147890_b(WorldRenderer.java:242)
        at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:158)
        at fastcraft.ab.a(F:518)
        at fastcraft.ag.a(F:125)
        at fastcraft.HC.t(F:77)
        at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
        at Reika.DragonAPI.ASM.ASMCallsClient.onRenderWorld(ASMCallsClient.java:86)
        at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
        at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
        at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
        at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
        at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)

is an example stack of the tesselator hang.  (Included for clarity for future searches of this problem running antique packs; Blu doesn't support 1.7.10 anymore).
